apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-admin-password: Z29raGFud2VsbDEyMzQ=
  mysql-root-password: UjEyMzRy

# gokhanwell1234 and R1234r code
#echo -n 'R1234r' | base64  
#echo -n 'gokhanwell1234' | base64 

# gokhanwell1234 and R1234r decode
# echo -n 'UjEyMzRy' | base64 --decode     
# echo -n 'Z29raGFud2VsbDEyMzQ=' | base64 --decode