apiVersion: v1
kind: Secret
metadata: 
    name: mysql-secret
type: Opaque
data: 
    mysql-admin-password: Z29raGFud2VsbDEyMzQ=
    mysql-root-password: UjEyMzRy



# gokhanwell1234 ve R1234r şifreleri önce encode edilmeli bunun için
#echo -n 'R1234r' | base64   --->  mysql-root-password olarak mysql-secret.yaml dostasında adreslenir
#echo -n 'gokhanwell1234' | base64 ----> mysql-admin-password olarak mysql-secret.yaml dostasında adreslenir

# gokhanwell1234 ve R1234r şifreleri decode etmek için
# echo -n 'UjEyMzRy' | base64 --decode     ---> It gives root us poassword
# echo -n 'Z29raGFud2VsbDEyMzQ=' | base64 --decode   ---> It gives us admin password